name: Email ID Action Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 23f2004721@ds.study.iitm.ac.in
        run: echo "Hello, world from GitHub Actions!"

